# Generated by Django 5.0.14 on 2025-07-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_auther"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="auther",
            new_name="author",
        ),
    ]
